name: 🐞 Bug Report
about: Open a new bug/issue report
title: "[BUG] <Enter bug title here>"
body:
- type: markdown
  attributes:
    value: "## Describe the bug/issue"
- type: markdown
  attributes:
    value: |
      Before raising a bug/issue please check that it has not already been reported
      by searching [existing issues](https://github.com/darktable-org/darktable/issues).
      
      Please be aware that most developers work on this project in their free time.
      The more information you can provide in the initial report the quicker we can help.
      Therefore please help by being as accurate and concise as possible!
      
      For further information, please see [Wiki on reporting bugs](https://github.com/darktable-org/darktable/wiki#reporting-bugs).
- type: textarea
  attributes:
    label: Current Behavior
    description: "A concise description of what you're experiencing."
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Please provide detailed steps to reproduce the behaviour,.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Backtrace, Screenshots & Screencasts
    description: |
      Drag&drop backtrace here (if darktable generated such file)
      Drag&drop logs (if you managed to gather them)
      Drag&drop screenshots here (if applicable)
      Drag&drop mp4/gif screen recordings or post links to screencasts hosted elsewhere (if applicable)
  validations:
    required: false
- type: markdown
  attributes:
    value: "## Platform"
- type: markdown
  attributes:
    value: |
      Please fill as much information as possible below.
      Please state "unknown" where you do not know the answer and remove any sections that are not applicable
- type: input
  attributes:
    label: Darktable version
    description: "Exact darktable version, eg `3.6.0`, `3.7.0+324~g17d82bb19`"
    placeholder: "this is darktable 3.7.0+324~g17d82bb19"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Operating system
    options:
      - Linux
      - macOS
      - Windows
      - "Other/issue happens on all"
  validations:
    required: true
- type: input
  attributes:
    label: Operating system version information
    description: "Exact operating system version, eg BigSur, Ubuntu 22.04, 11 Beta"
    placeholder: "Example: macOS BugSir, Ubuntu 22.04, Gentoo 5.10.27, 11 TechPreview"
  validations:
    required: true
- type: textarea
  attributes:
    label: Platform details
    description: 'Please state "unknown" where you do not know the answer and remove any sections that are not applicable'
    value: |
      * Memory            : 
      * Graphics card     : 
      * Graphics driver   : 
      * OpenCL installed  : 
      * OpenCL activated  : 
      * Xorg              : 
      * Desktop           : 
      * GTK+              : 
      * gcc               : 
      * cflags            : 
      * CMAKE_BUILD_TYPE  : 
    render: prose
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Additional information"
- type: markdown
  attributes:
    value: |
      Please provide any additional information you think may be useful
      
      If you are self-compilling, please try using `git bisect` to determine which commit introduced the issue and place the result here.
      A bisect is much appreciated and can significantly simplify the developer's job.
      HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A
- type: textarea
  attributes:
    label: Additional context
    description: |
      Please answer all applicable questions, remove those not applicable and add any additional info
      
      You can drop additional files here
    value: |
      - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
      - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
      - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
      - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
      - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
      - Do you use lua scripts?
        - What lua scripts start automatically?
        - What lua scripts were running when the bug occurred?
  validations:
    required: false
