# This is a basic workflow to help you get started with Actions

name: IRC Notification

# Controls when the workflow will run
on:
  #schedule:
  #- cron: "*/5 * * * *"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: src
      - uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: irc.yml
          name: recent_commit
      - name: git log
        id: gitlog
        run: |
          cd src;
          if [ ! -f ../recent_commit ]; then
            git log --format="%H" -n 1 --skip 10 > ../recent_commit
          fi;
          git log --format="%H" -n 1 > ../current_commit
          if cmp -s ../recent_commit ../current_commit; then
            echo "no new commits since last run"
            echo "::set-output name=log::"
          else
            git log --reverse --first-parent --pretty=format:"%h: %s (%aN)" `cat ../recent_commit`..`cat ../current_commit` >> ../log
            echo "current log:"
            cat ../log
            echo "";
            echo "setting output..."
            output="$(cat ../log)"
            output="${output//'%'/'%25'}"
            output="${output//$'\n'/'%0A'}"
            output="${output//$'\r'/'%0D'}"
            echo "::set-output name=log::$output"
            echo ""
            echo "::set-output name=llc::$(wc -l ../log)"
          fi;
          cd ..
          mv -f current_commit recent_commit
      - name: IRC notification
        if: ${{ steps.gitlog.outputs.log != '' }}
        uses: Gottox/irc-message-action@v2
        with:
          server: "irc.oftc.net"
          channel: '#dt-irc-test'
          nickname: dt-slav
          message: |-
            Heło, there be ${{ steps.gitlog.outputs.llc }} new commit(s):
            ${{ steps.gitlog.outputs.log }}
      - uses: actions/upload-artifact@v2
        with:
          name: recent_commit
          path: recent_commit
          if-no-files-found: warn
