# This is a basic workflow to help you get started with Actions

name: IRC Notification

# Controls when the workflow will run
on:
  #schedule:
  #- cron: "*/5 * * * *"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: src
      - uses: actions/download-artifact@v2
        with:
          name: recent_commit
          path: git_stats
      - name: Check for empty artifact
        if: ${{ failure() }}
        run: |
          cd src;
          git log --format="%H" -n 1 --skip 10 > ../git_stats/recent_commit
      - name: git log
        id: log
        run: |
          cd src;
          git log --format="%H" -n 1 > ../git_stats/current_commit
          if cmp -s ../git_stats/recent_commit ../git_stats/current_commit; then
            echo "no new commits since last run";
          else
            git log --first-parent --pretty=format:"%h: %s (%aN)" `cat ../git_stats/recent_commit`..`cat ../git_stats/current_commit`
          fi;
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          server: "irc.oftc.net"
          channel: '#dt-irc-test'
          nickname: dt-slav
          message: "test"
